#!/usr/bin/env bash

COMMAND="$1"
shift

if [ "$COMMAND" == "" ]; then
    echo "Error: command is missing"
    echo "Possible commands: clean, clean_tmp, reset, install, rights, composer_install, composer_update"
    echo " unittests,  shell, shellroot"
    echo " ldapreset, ldapusers"
    exit 1;
fi

CONTAINER_PREFIX=jelix_multiauth

case $COMMAND in
    clean_tmp)
        docker exec -t -i ${CONTAINER_PREFIX}_php appctl.sh clean_tmp;;
    clean)
        docker exec -t -i ${CONTAINER_PREFIX}_php appctl.sh clean;;
    reset)
        docker exec -t -i ${CONTAINER_PREFIX}_php appctl.sh reset;;
    install)
        docker exec -t -i ${CONTAINER_PREFIX}_php appctl.sh install;;
    install-module-dev)
        docker exec -it --user userphp ${CONTAINER_PREFIX}_php php /jelixapp/tests/testapp/dev.php module:configure multiauth
        docker exec -it --user userphp ${CONTAINER_PREFIX}_php php /jelixapp/tests/testapp/install/installer.php
        ;;
    install-module-local)
        docker exec -it --user userphp ${CONTAINER_PREFIX}_php php /jelixapp/tests/testapp/install/configurator.php multiauth
        docker exec -it --user userphp ${CONTAINER_PREFIX}_php php /jelixapp/tests/testapp/install/installer.php
        ;;
    rights)
        docker exec -t -i ${CONTAINER_PREFIX}_php appctl.sh rights;;
    composer-install)
        docker exec -it ${CONTAINER_PREFIX}_php appctl.sh composer_install;;
    composer-update)
        docker exec -t -i ${CONTAINER_PREFIX}_php appctl.sh composer_update;;
    unittests)
        docker exec -t -i ${CONTAINER_PREFIX}_php appctl.sh unittests;;
    shell)
       docker exec -it --user userphp ${CONTAINER_PREFIX}_php  /bin/bash -l;;
    shellroot)
       docker exec -it ${CONTAINER_PREFIX}_php  /bin/sh  -l;;
    ldapreset)
      docker exec -it ${CONTAINER_PREFIX}_ldap /bin/ctl.sh reset
      ;;
    ldapusers)
       docker exec -it ${CONTAINER_PREFIX}_ldap /bin/ctl.sh showusers
       ;;
    ldapshell)
      docker exec -it ${CONTAINER_PREFIX}_ldap  /bin/bash -l
      ;;

    *)
        echo "wrong command"
        exit 2
        ;;
esac

